api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('boats', views.BoatListView.as_view()),
    path('locations', views.getBoatLocations),
    path('boat/add', views.addBoat),
    path('settings', views.getSettings),
    path('boat/detail', views.getBoatDetail),
    path('boat/local', views.saveBoatLocalData),
    path('', views.getRecords),
    path('record/add', views.addRecord),
    path('boat/route', views.getBoatRoute),
    path('voyage/start', views.startVoyage),
    path('voyage/stop', views.stopVoyage),
    path('voyage/summary', views.summarizeVoyage),
]

seawavesserver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('monitoring/', include('monitoring.urls')),
    path('report/', include('reporting.urls')),
    path('', include('access.urls')),
]

monitoring/models.py
from django.db import models
from django.db.models import Max, Avg
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from datetime import date


class Adopter(models.Model):
    code = models.CharField(
        _("Adopter Code"), 
        max_length=6,
        unique=True
    )
    name = models.CharField(
        _("Adopter's Name"), 
        max_length=100
    )
    address = models.CharField(
        _("Adopter's Address"), 
        max_length=250
    )
    contact_person = models.CharField(
        _("Adopter's Contact Person"), 
        max_length=100
    )
    email = models.EmailField(
        _("Adopter's Email"),
        max_length=250
    )
    phone = models.CharField(
        _("Adopter's Phone"),
        max_length=50,
        null=True,
        blank=True,
        default=None
    )
    map_title = models.CharField(
        _("Map Title"),
        max_length=100,
        default="Map"
    )
    map_center_lat = models.FloatField(
        _("Map Center Latitude"),
        validators=[MinValueValidator(-90), MaxValueValidator(90)],
        default=0
    )
    map_center_lng = models.FloatField(
        _("Map Center Longitude"),
        validators=[MinValueValidator(-180), MaxValueValidator(180)],
        default=0
    )
    map_zoom = models.IntegerField(
        _("Map Zoom"),
        default=12
    )
    
    def __str__(self):
        return self.name


class Boat(models.Model):
    adopter = models.ForeignKey(
        Adopter, 
        verbose_name=_("Adopter"), 
        null=True,
        blank=True,
        default=None,
        on_delete=models.CASCADE
    )
    name = models.CharField(
        _("Boat's Name"), 
        max_length=100
    )
    owner = models.CharField(
        _("Owner's Name"), 
        max_length=250
    )
    owner_contact = models.CharField(
        _("Owner's Contact Number"), 
        max_length=50,
        null=True,
        blank=True,
        default=None
    )
    length = models.FloatField(
        _("Boat's Length"),
        help_text='(in meters)',
        validators=[MinValueValidator(0)]
    )
    width = models.FloatField(
        _("Boat's Width"),
        help_text='(in meters)',
        validators=[MinValueValidator(0)]
    )
    height = models.FloatField(
        _("Boat's Height"),
        help_text='(in meters)',
        validators=[MinValueValidator(0)]
    )
    registered_at = models.DateTimeField(
        _("Registered at"), 
        auto_now=False, 
        auto_now_add=True
    )
    is_active = models.BooleanField(
        _("Is active?"),
        default=True
    )

    class Meta:
        ordering = ['-registered_at']
        unique_together = ('name', 'owner', 'adopter')

    def __str__(self):
        return self.name
    
    @property
    def is_still_navigating(self):
        voyage = Voyage.objects.filter(boat=self).last()
        print(f"Voyage: {voyage}")
        if voyage:
            return voyage.get_ended_at() == None
        else:
            return False

    def last_location(self):
        last_record = self.record_set.last()
        return '%d, %d' % (last_record.latitude, last_record.longitude)
    
    def get_color(self):
        rec = Record.objects.filter(boat=self).last()
        if rec:
            return rec.getColor()
        else:
            return 'blue'
        

class Voyage(models.Model):
    boat = models.ForeignKey(
        Boat, 
        verbose_name=_("Boat"), 
        on_delete=models.CASCADE
    )
    started_at = models.DateTimeField(
        _("Started At"), 
        auto_now=False, 
        auto_now_add=True
    )
    ended_at = models.DateTimeField(
        _("Ended At"), 
        auto_now=False, 
        auto_now_add=False,
        null=True, blank=True, default=None
    )
    max_roll = models.FloatField(_("Maximum Roll"), default=0)
    max_pitch = models.FloatField(_("Maximum Pitch"), default=0)
    max_speed = models.FloatField(_("Maximum Speed"), default=0)
    avg_speed = models.FloatField(_("Average Speed"), default=0)
    

    def calculate_fields(self):
        records = Record.objects.filter(voyage=self)
        roll = 0
        pitch = 0
        for r in records:
            if abs(r.roll_angle) > roll: roll = r.roll_angle
            if abs(r.pitch_angle) > pitch: pitch = r.pitch_angle

        self.max_roll = roll
        self.max_pitch = pitch
        self.max_speed = records.aggregate(max=Max('speed'))['max']
        self.avg_speed = records.aggregate(avg=Avg('speed'))['avg']
        self.save()

    def get_ended_at(self):
        return self.ended_at if self.ended_at else None

    def __str__(self):
        ended = self.ended_at.strftime("%m/%d/%y %H:%M:%S") if self.ended_at else 'ongoing'
        return f'{self.boat.name} ({self.started_at.strftime("%m/%d/%y %H:%M:%S")} - {ended})'
    

class Record(models.Model):
    boat = models.ForeignKey(
        Boat, 
        verbose_name=_("Boat"), 
        on_delete=models.CASCADE
    )
    voyage = models.ForeignKey(
        Voyage, 
        verbose_name=_("Voyage"), 
        on_delete=models.CASCADE,
        null=True, blank=True, default=None
    )
    heading_angle = models.FloatField(
        _("Heading Angle"),
        help_text='(in degrees)',
    )
    pitch_angle = models.FloatField(
        _("Pitch Angle"),
        help_text='(in degrees)',
    )
    roll_angle = models.FloatField(
        _("Roll Angle"),
        help_text='(in degrees)',
    )
    gyro_x = models.FloatField(
        _("Gyroscope-X (Yaw Rate)"),
        help_text='(in degrees per second)',
    )
    gyro_y = models.FloatField(
        _("Gyroscope-Y (Roll Rate)"),
        help_text='(in degrees per second)',
    )
    gyro_z = models.FloatField(
        _("Gyroscope-Z (Pitch Rate)"),
        help_text='(in degrees per second)',
    )
    accel_x = models.FloatField(
        _("Acceleration-X"),
        help_text='(in meters per second)',
    )
    accel_y = models.FloatField(
        _("Acceleration-Y"),
        help_text='(in meters per second)',
    )
    accel_z = models.FloatField(
        _("Acceleration-Z"),
        help_text='(in meters per second)',
    )
    mag_x = models.FloatField(
        _("Magnetometer-X"),
        help_text='(in micro-Tesla)',
    )
    mag_y = models.FloatField(
        _("Magnetometer-Y"),
        help_text='(in micro-Tesla)',
    )
    mag_z = models.FloatField(
        _("Magnetometer-Z"),
        help_text='(in micro-Tesla)',
    )
    latitude = models.FloatField(
        _("Latitude"),
        help_text='(in degrees)',
    )
    longitude = models.FloatField(
        _("Longitude"),
        help_text='(in degrees)',
    )
    altitude = models.FloatField(
        _("Altitude"),
        help_text='(in meters)',
        default=0
    )
    signalStrength = models.PositiveSmallIntegerField()
    speed = models.FloatField(
        _("Speed"),
        help_text='(in m/s)',
        default=0
    )
    timestamp = models.DateTimeField(
        _("Time Received"), 
        auto_now=False, 
        auto_now_add=True
    )
    sent_timestamp = models.CharField(
        _("Time Sent"), 
        max_length=25
    )

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return '%s: %f° %f°' % (self.boat.name, self.latitude, self.longitude)

    def getColor(self):
        setting = Setting.objects.last()
        color = "blue"
        if setting:
            c_pitch = setting.critical_pitch_angle
            c_roll = setting.critical_roll_angle
            pitch_angle = abs(self.pitch_angle)
            roll_angle = abs(self.roll_angle)
            if pitch_angle >= c_pitch or roll_angle >= c_roll:
                color = "red"
            elif pitch_angle >= (c_pitch * 0.9) or roll_angle >= (c_roll * 0.9):
                color = "orange"
            elif pitch_angle >= (c_pitch * 0.8) or roll_angle >= (c_roll * 0.8):
                color = "yellow"
        return color
    

class LocalReadingAndError(models.Model):
    boat = models.ForeignKey(
        Boat, 
        verbose_name=_("Boat"), 
        on_delete=models.CASCADE
    )
    readings = models.TextField()
    errors = models.TextField(null=True, blank=True, default=None)
    recorded_on = models.DateField(auto_now=False, auto_now_add=True)
    


class Setting(models.Model):
    adopter = models.OneToOneField(
        Adopter, 
        verbose_name=_("Adopter"), 
        null=True,
        blank=True,
        default=None,
        on_delete=models.CASCADE,
    )
    critical_pitch_angle = models.FloatField(
        _("Critical Pitch Angle"),
        help_text='(in degrees)',
        default=15.0
    )
    critical_roll_angle = models.FloatField(
        _("Critical Roll Angle"),
        help_text='(in degrees)',
        default=20.0
    )
    reading_rate = models.FloatField(
        _("Reading Rate"),
        help_text='(in milliseconds)',
        default=250.0
    )
    saving_rate = models.FloatField(
        _("Saving Rate"),
        help_text='(in milliseconds)',
        default=60000.0
    )
    sms_rate = models.FloatField(
        _("SMS Rate"),
        help_text='(in milliseconds)',
        default=60000.0
    )
    post_rate = models.FloatField(
        _("Server Post Rate"),
        help_text='(in milliseconds)',
        default=60000.0
    )
    mobile_number = models.CharField(
        _("Mobile number for alarms"), 
        max_length=13
    )

    def __str__(self):
        return 'Setting #%d' % self.pk
    
    

class AvailableBulletin(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(available_until__gte=date.today())


class Bulletin(models.Model):
    adopter = models.ForeignKey(
        Adopter, 
        null=True,
        blank=True,
        default=None,
        verbose_name=_("Adopter"), 
        on_delete=models.CASCADE,
    )
    title = models.CharField(

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | SEAWAVES {{ user.userprofile.adopter.name }}</title>
  <link rel="icon" href="{% static 'img/seawaves_icon.png' %}">

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/94b023f88f.js" crossorigin="anonymous"></script>
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
  <!-- Toastr -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
  <!-- DataTable buttons -->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
  <style>
    .brand-link > span {
      color: black;
    }
  </style>
  {% block css %}{% endblock css %}
  
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
  
  {% block extra_header %}{% endblock extra_header %}  
    
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">
  
  {% block wrapper %}
  {% endblock wrapper %}
    

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-lg navbar-light navbar-white elevation-2 fixed-top primary">
    <!-- Brand Logo -->
     <a href="{% url 'dashboard' %}" class="brand-link d-flex align-items-center">
      <img src="{% static 'img/seawaves_logo_fit.png' %}" alt="Logo" class="brand-image me-2">
      <span class="brand-text">&nbsp;{{ user.userprofile.adopter.name }}</span>
    </a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Right navbar links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <!-- top navigation menu -->
        {% include 'includes/topmenu.html' %}
        <!-- full screen -->
        <li class="nav-item"> 
          <a class="nav-link" data-widget="fullscreen" href="#" role="button"> <i class="fas fa-expand-arrows-alt"></i> </a> 
        </li>
      </ul> 
    </nav>
  </div>
  <!-- /.navbar -->
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="margin-top: 80px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">{% block page_title %}{% endblock page_title %}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              {% block breadcrumb %}
              {% endblock breadcrumb %}                  
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    {% block main_content %}
    {% endblock main_content %}
        
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer no-print pb-2">
    <div class="float-left">
      <a target="_blank" href="{% url 'dashboard' %}" title="SEAWAVeS"><img class="mr-4" src="{% static 'img/seawaves_logo.png' %}" alt="SEAWAVeS" style="height: 70px; border: 1px"></a>
      <a target="_blank" href="http://asu.edu.ph/online/home/" title="Aklan State University (ASU)"><img class="mr-4" src="{% static 'img/logo_asu512.png' %}" alt="ASU" height="70px"></a>
      <a target="_blank" href="https://www.dost.gov.ph/" title="Department of Science and Technology (DOST)"><img class="mr-4" src="{% static 'img/logo_dost.png' %}" alt="DOST" height="70px"></a>
      <a target="_blank" href="http://pcieerd.dost.gov.ph/" title="Department of Science and Technology – Philippine Council for Industry, Energy, and Emerging Technology Research and Development (DOST-PCIEERD)"><img class="mr-4" src="{% static 'img/logo_dost_pcieerd.png' %}" alt="DOST-PCIEERD" height="70px"></a><br>
      <strong>Sea-condition Emergency Alert and Warning Apparatus for Vessel Safety</strong> (SEAWAVES)<br>
      <strong>Copyright &copy; 2022 <a href="https://asu.edu.ph/online/home/">Aklan State University - College of Industrial Technology</a>.</strong><br>
      <strong>All rights reserved.</strong> 
      <br>&nbsp;
    </div>
  </footer>
</div>
<div style="display: none;">
  {% if messages %}
    {% for message in messages %}
      <input type="hidden" class="message_notif" value="{{ message.tags }}:{{ message }}" />
    {% endfor %}
  {% endif %}
</div>
<!-- ./wrapper -->

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- Toastr -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<script type="text/javascript" src="https://momentjs.com/downloads/moment.min.js"></script>

<!-- DataTables -->
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.11.5/sorting/formatted-numbers.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>

<!-- <script src="{% static 'js/menu-selector.js' %}"></script> -->
<!-- <script src="{% static 'js/component-selector.js' %}"></script> -->
<!-- <script src="{% static 'js/notif-loader.js' %}"></script> -->
<script src="{% static 'js/toastr-loader.js' %}"></script>

<script>
  $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
    toastr.options = {
      closeButton: true,
      debug: false,
      newestOnTop: true,
      progressBar: false,
      positionClass: "toast-bottom-right",
      preventDuplicates: false,
      onclick: null,
      showDuration: "300",
      hideDuration: "1000",
      timeOut: "5000",
      extendedTimeOut: "1000",
      showEasing: "swing",
      hideEasing: "linear",
      showMethod: "fadeIn",
      hideMethod: "fadeOut",
    };
  });
</script>

{% block js %}
{% endblock js %}

</body>
</html>

templates/base_accounts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sign In | SEAWAVeS</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/94b023f88f.js" crossorigin="anonymous"></script>
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <link rel="icon" href="{% static 'img/seawaves_icon.png' %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  {% block card %}
  <div class="card card-outline card-primary">
  {% endblock card %}
    <div class="card-header">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <img src="{% static 'img/seawaves_logo_fit.png' %}" alt="SEAWAVeS Logo" width="100%"><br>
            <div class="text-center">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
        {% block content %}
        {% endblock content %}
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>


{% block js %}
{% endblock js %}
  
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}


{% block css %}
<style>
  .bulletin-title {
    font-size: larger;
    cursor: pointer;
  }
  .bulletin-info {
    font-size: small;
  }
  #map {
    height: 400px;
    /* The height is 400 pixels */
    width: 100%;
    /* The width is the width of the web page */
  }
</style>
{% endblock css %}  

{% block wrapper %}

{% endblock wrapper %}
  
{% block page_title %}Dashboard{% endblock page_title %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Home</li>
{% endblock breadcrumb %}
    

{% block main_content %}   

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Greeting section -->
        <div class="row mb-2">
          <div class="col-12">
            <h5>{{ greeting }}</h5>
          </div>
        </div>
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ boat_count }}</h3>

                <p>Active Boats</p>
              </div>
              <div class="icon">
                <i class="fas fa-ship"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{% widthratio setting.post_rate 1000 1 %} <sup style="font-size: 20px">seconds</sup></h3>

                <p>Posting Interval</p>
              </div>
              <div class="icon">
                <i class="fas fa-clock"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>{{ setting.critical_pitch_angle }}<sup style="font-size: 20px">°</sup></h3>

                <p>Critical Pitch Angle</p>
              </div>
              <div class="icon">
                <i class="fas fa-circle-exclamation"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>{{ setting.critical_roll_angle }}<sup style="font-size: 20px">°</sup></h3>

                <p>Critical Roll Angle</p>
              </div>
              <div class="icon">
                <i class="fas fa-triangle-exclamation"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
        
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-12 connectedSortable">
            <!-- Bulletin -->
            <div class="card">
              <div class="card-header border-0">
                <h3 class="card-title">
                  <i class="fas fa-thumbtack mr-1"></i>
                  Bulletin
                </h3>

                <div class="card-tools">
                  <button type="button" class="btn bg-info btn-sm" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn bg-info btn-sm" data-card-widget="remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
              <div class="card-body table-responsive">
                <table class="table table-sm">
                  
                  {% if not bulletin_list %}
                  <tr><td>The bulletin is clear. I think that's good news!</td></tr>
                  {% else %}
                  
                  {% for bulletin in bulletin_list %}
                  <tr><td>
                    <div class="bulletin-title text-primary" data-details="{{ bulletin.message }}">{{ bulletin.title }}</div>
                    <div class="bulletin-info text-muted">Posted at {{ bulletin.created_at }}</div>
                  </td></tr>  
                  {% endfor %}
                           
                  {% endif %}
                </table>
              </div>
              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
            
          </section>
          <!-- /.Left col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    
{% endblock main_content %}


{% block js %}
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- bootboxjs -->
<script src="{% static 'js/bootbox.all.min.js' %}"></script>

<!-- Google Maps -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<script>

  $(document).ready(function() {
      $("#menu_dashboard").addClass("active");

      $(".bulletin-title").click(function() {
        bootbox.dialog({
            title: $(this).text(),
            message: $(this).data('details')
        });
      });
  })
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFV4PqAS7hCB8KXmcZ6oM8XC9pJ1cK9GU&callback=initMap&v=weekly"></script>

{% endblock js %}
  